# Generated by Django 3.2.9 on 2021-12-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('F', 'Food'), ('AR', 'Appartment rent'), ('CL', 'Clothes'), ('OT', 'Other'), ('ED', 'Education')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('MW', 'Main work'), ('BS', 'Business'), ('OJ', 'Odd job')], max_length=2)),
            ],
        ),
    ]
