# Generated by Django 3.2.9 on 2021-12-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Appartment rent', 'Appartment rent'), ('Clothes', 'Clothes'), ('Other', 'Other'), ('Education', 'Education')], max_length=40),
        ),
    ]
